import { useEffect, useMemo, useState } from 'react';
import NiceModal, { useModal } from '@ebay/nice-modal-react';
import { useTranslation } from 'react-i18next';
import type { Diff } from 'shared/types';
import { attemptsApi } from '@/lib/api';
import { defineModal } from '@/lib/modals';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

export interface MergeCommitDialogProps {
  attemptId: string;
  repoId: string;
  defaultMessage: string;
  diffs?: Diff[]; // 现在可选，优先使用增量 diff
  taskTitle?: string;
  taskDescription?: string | null;
  targetBranch?: string | null;
  autoGenerate?: boolean;
}

export type MergeCommitDialogResult = {
  action: 'confirmed' | 'canceled';
  commitMessage?: string;
};

const MAX_DIFF_CONTEXT_CHARS = 12000;
const MAX_FILE_CONTENT_CHARS = 2000;

const truncate = (value: string, limit: number) => {
  if (value.length <= limit) return value;
  return `${value.slice(0, limit)}\n... [truncated]`;
};

const summarizeDiffs = (diffs: Diff[]) => {
  const summary = diffs.reduce(
    (acc, diff) => {
      acc.filesChanged += 1;
      acc.linesAdded += diff.additions ?? 0;
      acc.linesRemoved += diff.deletions ?? 0;
      return acc;
    },
    { filesChanged: 0, linesAdded: 0, linesRemoved: 0 }
  );

  return summary;
};

const buildDiffContext = (diffs: Diff[]) => {
  if (diffs.length === 0) return '';

  let totalChars = 0;
  const sections: string[] = [];

  for (const diff of diffs) {
    const path = diff.newPath || diff.oldPath || 'unknown';
    let section = `File: ${path}\nChange: ${diff.change}\n`;

    if (diff.contentOmitted) {
      section += `Content omitted. Additions: ${diff.additions ?? 0}, Deletions: ${diff.deletions ?? 0}\n`;
    } else {
      if (diff.oldContent != null) {
        section += `--- Old\n${truncate(diff.oldContent, MAX_FILE_CONTENT_CHARS)}\n`;
      }
      if (diff.newContent != null) {
        section += `--- New\n${truncate(diff.newContent, MAX_FILE_CONTENT_CHARS)}\n`;
      }
    }

    section += '\n';

    if (totalChars + section.length > MAX_DIFF_CONTEXT_CHARS) {
      sections.push('... diff context truncated ...');
      break;
    }

    sections.push(section);
    totalChars += section.length;
  }

  return sections.join('\n');
};

const buildPrompt = ({
  taskTitle,
  taskDescription,
  targetBranch,
  diffSummary,
}: {
  taskTitle?: string;
  taskDescription?: string | null;
  targetBranch?: string | null;
  diffSummary: { filesChanged: number; linesAdded: number; linesRemoved: number };
}) => {
  const title = taskTitle?.trim() || 'Untitled task';
  const description = taskDescription?.trim() || 'None';
  const branch = targetBranch?.trim() || 'unknown';

  return [
    '你是一个 Git 提交信息生成器。',
    '请生成中文的标准 Git commit message（用于合并到目标分支）。',
    '',
    '规则：',
    '- 只输出提交信息本体，不要附加解释、编号或代码块。',
    '- 第一行使用 Conventional Commits 格式，例如：',
    '  fix(ui): 修复按钮点击无响应问题',
    '  docs: 更新API接口文档',
    '  refactor(core): 重构登录模块代码结构',
    '- 第一行尽量简洁（<= 72 字符）。',
    '- 如需正文，第二行留空，从第三行开始写 1-3 句中文说明（可用整句，不强制列表）。',
    '- 重点说明“改了什么、为什么改”。避免泛泛的“更新文件/合并分支”。',
    '',
    `任务标题：${title}`,
    `任务描述：${description}`,
    `目标分支：${branch}`,
    `变更概要：文件 ${diffSummary.filesChanged} 个，新增 ${diffSummary.linesAdded} 行，删除 ${diffSummary.linesRemoved} 行`,
    '',
    '变更内容在下方 diff 中。',
  ].join('\n');
};

const MergeCommitDialogImpl = NiceModal.create<MergeCommitDialogProps>(
  ({
    attemptId,
    repoId,
    defaultMessage,
    diffs,
    taskTitle,
    taskDescription,
    targetBranch,
    // autoGenerate,
  }) => {
    const modal = useModal();
    const { t } = useTranslation(['tasks', 'common']);
    const [message, setMessage] = useState(defaultMessage);
    const [isGenerating, setIsGenerating] = useState(false);
    const [generateError, setGenerateError] = useState<string | null>(null);
    const [incrementalDiffs, setIncrementalDiffs] = useState<Diff[] | null>(null);
    const [loadingDiffs, setLoadingDiffs] = useState(false);
    // const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

    // 获取增量 diff
    useEffect(() => {
      if (modal.visible && !incrementalDiffs) {
        setLoadingDiffs(true);
        attemptsApi
          .getIncrementalDiff(attemptId, repoId)
          .then((response) => {
            setIncrementalDiffs(response.diffs);
          })
          .catch((error) => {
            console.error('Failed to fetch incremental diff:', error);
            // 如果获取失败，使用传入的 diffs 作为回退
            setIncrementalDiffs(diffs || []);
          })
          .finally(() => {
            setLoadingDiffs(false);
          });
      }
    }, [modal.visible, attemptId, repoId, incrementalDiffs, diffs]);

    // 每次弹窗显示时重置状态
    useEffect(() => {
      if (modal.visible) {
        setMessage(defaultMessage);
        setGenerateError(null);
        // 重置增量 diffs，触发重新获取
        setIncrementalDiffs(null);
      }
    }, [modal.visible, defaultMessage]);

    // 优先使用增量 diffs，回退到传入的 diffs
    const activeDiffs = incrementalDiffs || diffs || [];
    const diffSummary = useMemo(() => summarizeDiffs(activeDiffs), [activeDiffs]);
    const diffContext = useMemo(() => buildDiffContext(activeDiffs), [activeDiffs]);
    const prompt = useMemo(
      () =>
        buildPrompt({
          taskTitle,
          taskDescription,
          targetBranch,
          diffSummary,
        }),
      [taskTitle, taskDescription, targetBranch, diffSummary]
    );

    const canGenerate = diffContext.trim().length > 0 && !isGenerating && !loadingDiffs;

    const doGenerate = async () => {
      if (isGenerating) return;
      if (diffContext.trim().length === 0) return;
      setGenerateError(null);
      setIsGenerating(true);
      try {
        const response = await attemptsApi.generateMergeCommitMessage(attemptId, {
          repo_id: repoId,
          prompt,
          diff_context: diffContext,
        });
        if (response.message?.trim()) {
          setMessage(response.message.trim());
        }
      } catch (error) {
        const msg =
          error && typeof error === 'object' && 'message' in error
            ? String(error.message)
            : t('git.mergeCommitDialog.generateError');
        setGenerateError(msg);
      } finally {
        setIsGenerating(false);
      }
    };

    // 自动生成提交信息（暂时禁用）
    // useEffect(() => {
    //   if (autoGenerate && !hasAutoGenerated && diffContext.trim().length > 0) {
    //     setHasAutoGenerated(true);
    //     doGenerate();
    //   }
    // }, [autoGenerate, hasAutoGenerated, diffContext]);

    const handleGenerate = () => {
      doGenerate();
    };

    const handleConfirm = () => {
      if (!message.trim()) return;
      modal.resolve({
        action: 'confirmed',
        commitMessage: message.trim(),
      } as MergeCommitDialogResult);
      modal.hide();
    };

    const handleCancel = () => {
      modal.resolve({ action: 'canceled' } as MergeCommitDialogResult);
      modal.hide();
    };

    const handleOpenChange = (open: boolean) => {
      if (!open) {
        handleCancel();
      }
    };

    return (
      <Dialog open={modal.visible} onOpenChange={handleOpenChange}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{t('git.mergeCommitDialog.title')}</DialogTitle>
            <DialogDescription>
              {t('git.mergeCommitDialog.description')}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3">
            <div className="space-y-2">
              <label htmlFor="merge-commit-message" className="text-sm font-medium">
                {t('git.mergeCommitDialog.messageLabel')}
              </label>
              <Textarea
                id="merge-commit-message"
                value={message}
                onChange={(event) => setMessage(event.target.value)}
                placeholder={t('git.mergeCommitDialog.messagePlaceholder')}
                rows={6}
              />
              {generateError && (
                <p className="text-xs text-destructive">{generateError}</p>
              )}
            </div>

            <div className="flex items-center gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleGenerate}
                disabled={!canGenerate}
              >
                {isGenerating
                  ? t('git.mergeCommitDialog.generating')
                  : t('git.mergeCommitDialog.generate')}
              </Button>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={handleCancel}>
              {t('common:buttons.cancel')}
            </Button>
            <Button onClick={handleConfirm} disabled={!message.trim()}>
              {t('git.mergeCommitDialog.confirm')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    );
  }
);

export const MergeCommitDialog = defineModal<
  MergeCommitDialogProps,
  MergeCommitDialogResult
>(MergeCommitDialogImpl);
